### ISSUE TITLE
Incorrect output

### ISSUE THREAD

**Issue by X00107578** [ocawley/ittsqa22#15]
The expected output for grades 80 and 80 should be "pass with distinction" but it is only "pass".

**Comment by ocawley** [comment]
Fixed issue please verify.

**Comment by X00107578** [comment]
Issue not fixed! The output is now omitted!

**Comment by X00107578** [comment]
Issue not fixed! The output is now omitted! Please, fix this issue.
